### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by SOCO69420** [rouyng/airspotbot#40]
I need some help understanding this:

14-May-23 23:22:34 - airspotbot - INFO: Authentication OK
14-May-23 23:22:34 - airspotbot - INFO: Twitter API v1.1 client created
Traceback (most recent call last):
  File "/home/adsb/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/adsb/airspotbot/airspotbot/__main__.py", line 63, in <module>
    airspotbot.run_bot(config_path=args.config,
  File "/home/adsb/airspotbot/airspotbot/airspotbot.py", line 292, in run_bot
    bot = SpotBot(config_parsed=config,
  File "/home/adsb/airspotbot/airspotbot/airspotbot.py", line 63, in __init__
    self.screenshotter = screenshot.Screenshotter(self.zoom_level)
  File "/home/adsb/airspotbot/airspotbot/screenshot.py", line 33, in __init__
    self.driver = self._start_webdriver()
  File "/home/adsb/airspotbot/airspotbot/screenshot.py", line 65, in _start_webdriver
    driver = webdriver.Chrome(options=options)
  File "/home/adsb/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/adsb/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/adsb/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by rouyng** [comment]
You need to have chromedriver installed and the executable must be in a directory specified by the system PATH variable.
See [https://chromedriver.chromium.org/getting-started](https://chromedriver.chromium.org/getting-started) for more info on installing chromedriver.

**Comment by HENRY1soco** [comment]
> You need to have chromedriver installed and the executable must be in a directory specified by the system PATH variable. See https://chromedriver.chromium.org/getting-started for more info on installing chromedriver.

That was an easy fix... Thank you for the guidance!
